name: 🎥 YouTube Downloader (Artifacts)

on:
  workflow_dispatch:
    inputs:
      youtube_url:
        description: '🔗 YouTube Video URL'
        required: true
        type: string

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg
          sudo curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o /usr/local/bin/yt-dlp
          sudo chmod a+rx /usr/local/bin/yt-dlp

      - name: 🚀 Download video
        env:
          URL: ${{ github.event.inputs.youtube_url }}
        run: |
          mkdir -p downloads
          # دانلود بهترین کیفیت
          yt-dlp \
            -f "bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best" \
            --merge-output-format mp4 \
            --restrict-filenames \
            -o "downloads/%(title)s.%(ext)s" \
            "$URL"

      - name: 📦 Upload Video as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: YouTube-Video
          path: downloads/
          retention-days: 5 # فایل بعد از ۵ روز از سرور گیت‌هاب پاک می‌شود
