name: Download And Save

on:
  workflow_dispatch:
    inputs:
      file_url:
        description: 'File URL'
        required: true

jobs:
  download:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Download file
        run: |
          URL="${{ github.event.inputs.file_url }}"
          FILENAME=$(basename "$URL")
          curl -L "$URL" -o "$FILENAME"
          echo "FILENAME=$FILENAME" >> $GITHUB_ENV

      - name: Upload artifact (backup)
        uses: actions/upload-artifact@v4
        with:
          name: downloaded-file
          path: ${{ env.FILENAME }}

      - name: Commit to repo
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add "${{ env.FILENAME }}"
          git commit -m "add downloaded file"
          git push
